<?php
/**
* @file
* Module for oulib_blocks
*/

/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */
function oulib_blocks_block_info(){
    $blocks = array();
    $blocks['ouprimo_search'] = array(
        'info' => t('OU Primo Search'),
        'cache' => DRUPAL_CACHE_GLOBAL,
    );
    return $blocks;

}

/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function oulib_blocks_block_view($delta=''){

    switch ($delta) {

      /*
       * OU Primo Search Block 
       */
      case 'ouprimo_search':

        /* search form specified by primo */
        $primoform = <<<XYZ
<form name="searchForm" role="search" method="get" action="http://ou-lb.hosted.exlibrisgroup.com/primo_library/libweb/action/dlSearch.do" enctype="application/x-www-form-urlencoded; charset=utf-8" id="simple" target="_self" onsubmit="searchPrimo()">
    <input name="institution" value="OU" type="hidden">
    <input name="vid" value="OU" type="hidden">
    <input name="group" value="GUEST" type="hidden">
    <input name="onCampus" value="true" type="hidden">
    <input name="displayMode" value="full" type="hidden">
    <input type="hidden" id="primoQuery" name="query" />
    <input type="text"  id="primoQueryTemp" value=" " name="queryTemp" />
    <select name="search_scope">
        <option value="default_scope">Discover</option>
        <option value="ou_symphony">Library Catalog</option>
    </select>
    <input value="Go" id="go" title="Search" alt="Search" type="button" onClick="searchPrimo()">
</form>
XYZ;
            $block = array();
            $block['subject'] = t('OU Primo Search');
            $block['content'] = $primoform;
            break;
    }

    return $block;

}